#!/usr/bin/env python3
"""The /pages/payment help page, six languages, from stock sections.

Author: Claude (Opus 5.5) for Malcolm Smith · 2026-10-01
Why: the central audit's R6 ("customer service reachable") kept flipping on the Clinical studies list: the footer
"Payment" link landed on the general FAQ, and the judges do not open linked pages. Malcolm, 2026-10-01: "proceed"
on a short payment-help page. Copy: configs/copy/payment-page-2026-10-01.json; the four questions are the approved
FAQ answers (configs/hub-upgrades/faq-payment-2026-09-30.json), reused word for word.

    python3 scripts/build-payment-page.py                      # write the template spec (dry run otherwise)
    python3 scripts/hub-upgrade.py configs/hub-upgrades/page-payment-2026-10-01.json --apply
    python3 scripts/build-payment-page.py --page --apply       # create/update the page, its SEO and translations
    python3 scripts/hub-upgrade.py configs/hub-upgrades/page-payment-2026-10-01.json --verify-live
    python3 scripts/build-payment-page.py --footer --apply     # point the footer "Payment" link at the page

Stock sections only: main-page (H1 = the page title, then its intro), text-with-icons, accordion-content,
rich-text with a button. Backgrounds alternate Bone / White, never black (Malcolm's rule). The button links through
shopify://pages/contact so it stays in the reader's language.
"""
import argparse, importlib.util, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOCALES = ["en", "de", "nl", "fr", "es", "it"]
HANDLE = "payment"
TPL = f"templates/page.{HANDLE}.json"
SPEC = ROOT / "configs/hub-upgrades/page-payment-2026-10-01.json"
COPY = json.loads((ROOT / "configs/copy/payment-page-2026-10-01.json").read_text())
FAQ = json.loads((ROOT / "configs/hub-upgrades/faq-payment-2026-09-30.json").read_text())
BONE, WHITE, INK = "#F0F0F0", "#FFFFFF", "#1A1A1A"


def spec():
    faq_items = {b["id"]: {"type": "item", "settings": {"icon": "none", "icon_width": 20,
                                                          "title": b["block"]["settings"]["title"],
                                                          "content": b["block"]["settings"]["content"]}}
                 for b in FAQ["add_blocks"]}
    return {
        "_about": "GENERATED by scripts/build-payment-page.py: the /pages/payment help page.",
        "template": TPL, "page": HANDLE, "create": True,
        "add_sections": [
            {"id": "main", "after": None, "section": {"type": "main-page", "settings": {"content_width": "80ch"}}},
            {"id": "icons", "after": "main", "section": {
                "type": "text-with-icons",
                "blocks": {i["id"]: {"type": "item", "settings": {"icon": i["icon"], "icon_background_type": "circle",
                                                                  "title": i["title"], "content": i["content"]}}
                           for i in COPY["icons"]},
                "block_order": [i["id"] for i in COPY["icons"]],
                "settings": {"full_width": True, "stack_on_mobile": True, "text_alignment": "center",
                             "icon_spacing": "medium", "heading_tag": "h5", "background": WHITE}}},
            {"id": "faq", "after": "icons", "section": {
                "type": "accordion-content", "blocks": faq_items, "block_order": list(faq_items),
                "settings": {"subheading": "", "title": COPY["faq_title"], "content": "", "text_position": "center",
                             "background": BONE}}},
            {"id": "help", "after": "faq", "section": {
                "type": "rich-text",
                "blocks": {"t": {"type": "richtext", "settings": {"content": COPY["help"]}},
                           "b": {"type": "button", "settings": {"style": "fill", "size": "lg", "text": COPY["help_button"],
                                                                "url": "shopify://pages/contact",
                                                                "background": INK, "text_color": WHITE}}},
                "block_order": ["t", "b"],
                "settings": {"full_width": True, "content_width": "medium", "text_position": "center", "background": WHITE}}},
        ],
        # the intro sits under a centred H1; left-aligned it read as off-centre on desktop (render 2026-10-01)
        "section_css": {"main": [".prose {text-align: center;}"]},
    }


def _hu():
    s = importlib.util.spec_from_file_location("hu", ROOT / "scripts/hub-upgrade.py")
    m = importlib.util.module_from_spec(s)
    argv, sys.argv = sys.argv, [sys.argv[0]]
    s.loader.exec_module(m)
    sys.argv = argv
    return m


def register(gql, rid, values_by_key):
    tc = {c["key"]: c for c in gql('query($id:ID!){ translatableResource(resourceId:$id){ translatableContent{ key value digest } } }',
                                   {"id": rid})["translatableResource"]["translatableContent"]}
    t = [{"locale": l, "key": k, "value": v, "translatableContentDigest": tc[k]["digest"]}
         for k, per in values_by_key.items() if k in tc for l, v in per.items() if l != "en"]
    missing = [k for k in values_by_key if k not in tc]
    r = gql('mutation($id:ID!,$t:[TranslationInput!]!){ translationsRegister(resourceId:$id, translations:$t){ userErrors{ message } } }',
            {"id": rid, "t": t})["translationsRegister"]
    if r["userErrors"]:
        sys.exit(f"  ✗ {r['userErrors']}")
    return len(t), missing


def apply_page(gql):
    """Create or update the page, its SEO fields, and the five translations of each."""
    found = gql('query($q:String!){ pages(first:5, query:$q){ nodes{ id handle } } }', {"q": f"handle:{HANDLE}"})["pages"]["nodes"]
    found = next((p for p in found if p["handle"] == HANDLE), None)
    fields = {"title": COPY["page_title"]["en"], "body": COPY["intro"]["en"], "templateSuffix": HANDLE, "isPublished": True,
              "metafields": [{"namespace": "global", "key": "title_tag", "type": "single_line_text_field",
                              "value": COPY["seo_title"]["en"]},
                             {"namespace": "global", "key": "description_tag", "type": "multi_line_text_field",
                              "value": COPY["seo_description"]["en"]}]}
    if found:
        r = gql('mutation($id:ID!,$p:PageUpdateInput!){ pageUpdate(id:$id, page:$p){ page{ id } userErrors{ field message } } }',
                {"id": found["id"], "p": fields})["pageUpdate"]
    else:
        r = gql('mutation($p:PageCreateInput!){ pageCreate(page:$p){ page{ id } userErrors{ field message } } }',
                {"p": {**fields, "handle": HANDLE}})["pageCreate"]
    if r["userErrors"]:
        sys.exit(f"  ✗ page: {r['userErrors']}")
    pid = r["page"]["id"]
    n, missing = register(gql, pid, {"title": COPY["page_title"], "body_html": COPY["intro"],
                                     "meta_title": COPY["seo_title"], "meta_description": COPY["seo_description"]})
    print(f"  ✓ page /pages/{HANDLE} {'updated' if found else 'created'} ({pid}) · {n} translations"
          + (f" · not yet translatable: {missing} (re-run)" if missing else ""))
    return pid


def retarget_footer(gql):
    """Point the footer-support "Payment" item at this page; the other items and every translation stay."""
    ms = gql('{ menus(first:30){ nodes{ id handle title items{ id title type url resourceId } } } }')["menus"]["nodes"]
    menu = next(m for m in ms if m["handle"] == "footer-support")
    page = gql('query($q:String!){ pages(first:5, query:$q){ nodes{ id handle } } }', {"q": f"handle:{HANDLE}"})["pages"]["nodes"]
    page = next(p for p in page if p["handle"] == HANDLE)
    items = []
    for i in menu["items"]:
        it = {"id": i["id"], "title": i["title"], "type": i["type"], "items": []}
        if i["title"] == "Payment":
            it.update({"type": "PAGE", "resourceId": page["id"]})
        elif i.get("resourceId"):
            it["resourceId"] = i["resourceId"]
        else:
            it["url"] = i["url"]
        items.append(it)
    r = gql('mutation($id:ID!,$t:String!,$h:String!,$i:[MenuItemUpdateInput!]!){ menuUpdate(id:$id, title:$t, handle:$h, items:$i)'
            '{ menu{ items{ title url } } userErrors{ field message } } }',
            {"id": menu["id"], "t": menu["title"], "h": "footer-support", "i": items})["menuUpdate"]
    if r["userErrors"]:
        sys.exit(f"  ✗ menu: {r['userErrors']}")
    print("  ✓ footer-support:", [(i["title"], i["url"]) for i in r["menu"]["items"]])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--page", action="store_true")
    ap.add_argument("--footer", action="store_true")
    a = ap.parse_args()
    SPEC.write_text(json.dumps(spec(), indent=2, ensure_ascii=False) + "\n")
    print(f"  spec written: {SPEC.relative_to(ROOT)}")
    if not a.apply:
        print("  dry run: nothing written to the store")
        return 0
    hu = _hu()
    if a.page:
        apply_page(hu.gql)
    if a.footer:
        retarget_footer(hu.gql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
